# @see https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - 3.6

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1

before_install:

  # Install some built-in modules that appear to be missing.
  - pip install python-dateutil

  # Avoid deprecation notices when using pip list - looks like Travis has an older version of pip.
  # @see https://pip.pypa.io/en/stable/user_guide/#config-file
  # @see https://pip.pypa.io/en/stable/reference/pip_list/#options
  - mkdir --parents ~/.config/pip
  - echo '[list]\nformat=columns' >> ~/.config/pip/pip.conf

install:
  - make install

script:
  - make test

after_success:
  - make coverage

notifications:
  email: false
  slack:
    rooms:
      - secure: Td8ScZpJPfmOf81IxiG5fWFHo/H+h8765u6c27J9hcZTI+0uG/iFjavWHC3R7ClUT4+AXcOZsTB9rHIWBKQ7+iVZ/kNEObDdYb+YNlAvHeAEdkurKooG/aBXzmO9tU6AnPFG44aDDgzybt4rL3fVgiytVauhxHONYCXdMKjf91OEOjuNO+Ufd6455w8AgD1aMUtGglDNfAOu60irrkhSuWtdvswkLWIjZZpxLYhxTGou/Wc8OMz2cpaxNW2KPePD1ALpX/8Y5bBHZqXEM7jVnx44CJ8i/qd5OEYhJb4qy9bBLeTw0JerN8p9DCkTmP43ZsMNyQQ2KeBxsln36DMZtRn0pS2d0d+n20LGyUetShB9iN9OpvfH8KtN1iRB1VSDGr+vYvghaUb9JodjyW/0NPBWWeSHry6DVE6V5hZYn8msgY6H5Nbb19tIzmz3D9gqP90Mt55nEclrxUa/gc1kgCoGL8Y5QTqPGo7BMyNwIiqpuWOsVch75GRYumO0LYOmn30gM6sm63BlL0eF8+9fNFNdgTtSupXR4mrXYZ8M4J8uBWoD6VoEaMfuWUsu/cvue3zH/oyjXBq7r1knjnjwyfd1bf6uDdl7+8SkvdlwEth0zFIDAy/AfuW4t+l7TbfxQUydI9DtWUO4Mn3Bf1ZPND4YovAlp6duUp30vzreeiw=
    on_start: always
